# ===================================================================
# PERFIL ACTIVO POR DEFECTO
# ===================================================================
spring.profiles.active=local

# ===================================================================
# CONFIGURACIÓN DE POSTGRESQL (RENDER - PRODUCCIÓN / NUBE)
# ===================================================================
spring.datasource.url=jdbc:postgresql://dpg-d8hipckvikkc73f9t990-a.ohio-postgres.render.com:5432/compra_venta_propiedades?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=root
spring.datasource.password=rdpVJvGoei88zpABzdcFy4X0mikeiQ0q
spring.datasource.driver-class-name=org.postgresql.Driver

# Tiempos de espera optimizados para evitar caídas por latencia
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# Configuración de Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Estrategias de nombrado estándar de Spring Boot
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl

# Logging para auditoría de queries
logging.level.org.hibernate.orm.jdbc.bind=trace

# ===================================================================
# CONFIGURACIÓN DE MONGODB (ATLAS - NUBE)
# ===================================================================
spring.data.mongodb.uri=mongodb+srv://Juan:dracov3@cluster0.momwvdc.mongodb.net/compra_venta_chats?retryWrites=true&w=majority&appName=Cluster0

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter=TRACE
logging.level.com.compraventap=DEBUG